name: Java CI with Maven - Test and package
on:  # Ce workflow se déclenche sur un pull request dans le dépôt
  pull_request:
    branches:
      - main


jobs:
  build:
    name: Test and package
    runs-on: ubuntu-latest  # OS où s'exécute le job
    steps:
      - name: dépôt courant
        uses: actions/checkout@v4

      - name: version java
        uses: actions/setup-java@v4
        with:
            distribution: 'corretto'
            java-version: 21

      - name: maven et tests
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  # le jeton d'accès
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=$(echo ${{ github.repository }} | sed 's-/-_-')

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
            path: ~/.m2/repository
            key: ${{ runner.os }}-maven-${{hashFiles('**/pom.xml') }}
            restore-keys: |
                ${{ runner.os }}-maven-

      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonarqube-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
           ${{ runner.os }}-sonarqube-

